// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import {PayrollRun} from "../src/PayrollRun.sol";
import {MockUSDG} from "./mocks/MockUSDG.sol";

/**
 * @title Solidity <-> JavaScript parity.
 *
 * The vector in `test/vectors/parity.json` is generated by the SAME module the frontend uses
 * (`app/lib/merkle.js`), then re-derived here from the raw inputs and checked against the
 * contract's own `leafFor` and OpenZeppelin's `MerkleProof`.
 *
 * If the two implementations ever drift — a changed tag, `encodePacked` vs `encode`, hex-string
 * instead of numeric pair sorting, duplicating an odd node instead of carrying it up — this test
 * fails. It is also executed end-to-end against `claim()` below, so parity is proven against the
 * real claim path, not just a hash comparison.
 */
contract ParityTest is Test {
    PayrollRun internal payroll;
    MockUSDG internal usdg;

    address internal employer = address(0xE47);
    string internal json;

    function setUp() public {
        usdg = new MockUSDG();
        payroll = new PayrollRun(address(usdg));
        usdg.mint(employer, 10_000_000e6);

        vm.prank(employer);
        usdg.approve(address(payroll), type(uint256).max);

        json = vm.readFile("test/vectors/parity.json");
    }

    function _u(string memory path) internal view returns (uint256) {
        return vm.parseJsonUint(json, path);
    }

    function _s(string memory path) internal view returns (string memory) {
        return vm.parseJsonString(json, path);
    }

    function test_parity_leafTagMatchesContractConstant() public view {
        assertEq(
            _s(".leafTag"),
            HexTag.hexOf(payroll.LEAF_TAG()),
            "LEAF_TAG drifted between JS and Solidity"
        );
    }

    function test_parity_everyJsLeafMatchesContractLeafFor() public view {
        uint256 n = _u(".leafCount");
        assertGt(n, 0, "vector is empty");

        for (uint256 i = 0; i < n; i++) {
            uint256 index = _u(string.concat(".entries[", vm.toString(i), "].index"));
            address claimant = vm.parseJsonAddress(json, string.concat(".entries[", vm.toString(i), "].claimant"));
            uint256 amount = _u(string.concat(".entries[", vm.toString(i), "].amount"));
            bytes32 salt = vm.parseJsonBytes32(json, string.concat(".entries[", vm.toString(i), "].salt"));
            bytes32 jsLeaf = vm.parseJsonBytes32(json, string.concat(".entries[", vm.toString(i), "].leaf"));

            assertEq(
                payroll.leafFor(_u(".runId"), index, claimant, amount, salt),
                jsLeaf,
                "JS leaf differs from contract leafFor"
            );
        }
    }

    function test_parity_everyJsProofVerifiesWithOpenZeppelin() public view {
        bytes32 root = vm.parseJsonBytes32(json, ".root");
        uint256 n = _u(".leafCount");

        for (uint256 i = 0; i < n; i++) {
            bytes32 leaf = vm.parseJsonBytes32(json, string.concat(".entries[", vm.toString(i), "].leaf"));
            bytes32[] memory proof =
                vm.parseJsonBytes32Array(json, string.concat(".entries[", vm.toString(i), "].proof"));

            assertTrue(
                MerkleProof.verify(proof, root, leaf),
                "a JS-generated proof failed OZ verification"
            );
        }
    }

    /// @dev Proves the JS root against an independently derived one, using the odd-node rule.
    function test_parity_jsRootMatchesIndependentlyDerivedRoot() public view {
        bytes32[] memory leaves = new bytes32[](_u(".leafCount"));
        for (uint256 i = 0; i < leaves.length; i++) {
            leaves[i] = vm.parseJsonBytes32(json, string.concat(".entries[", vm.toString(i), "].leaf"));
        }

        bytes32 derived = _fold(leaves);
        assertEq(derived, vm.parseJsonBytes32(json, ".root"), "JS root differs from Solidity fold");
    }

    /// @dev Rebuilds the tree level by level; odd node carried up unchanged (never duplicated).
    function _fold(bytes32[] memory level) internal pure returns (bytes32) {
        while (level.length > 1) {
            bytes32[] memory next = new bytes32[]((level.length + 1) / 2);
            for (uint256 i = 0; i < level.length; i += 2) {
                if (i + 1 == level.length) {
                    next[i / 2] = level[i];
                } else {
                    next[i / 2] = _hashPair(level[i], level[i + 1]);
                }
            }
            level = next;
        }
        return level[0];
    }

    function _hashPair(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return a < b ? keccak256(abi.encodePacked(a, b)) : keccak256(abi.encodePacked(b, a));
    }

    function test_parity_totalMatchesSumOfEntries() public view {
        uint256 n = _u(".leafCount");
        uint256 sum = 0;
        for (uint256 i = 0; i < n; i++) {
            sum += _u(string.concat(".entries[", vm.toString(i), "].amount"));
        }
        assertEq(sum, _u(".total"), "JS total is not the sum of its entries");
    }

    /// @dev The real thing: every JS-built package must actually pay out through `claim()`.
    ///      With 5 leaves this also exercises an ODD level, where the carry-up rule matters.
    function test_parity_fullRosterClaimsOnChain() public {
        uint64 deadline = uint64(block.timestamp + 30 days);
        bytes32 root = vm.parseJsonBytes32(json, ".root");
        uint256 runId = _u(".runId");

        // the vector's runId is 7; run 1..6 must exist first for the ids to line up
        for (uint256 i = 0; i < runId - 1; i++) {
            vm.prank(employer);
            payroll.createRun(keccak256(abi.encode("placeholder", i)), deadline, 1e6);
        }

        vm.prank(employer);
        uint256 created = payroll.createRun(root, deadline, _u(".total"));
        assertEq(created, runId, "run id mismatch");

        uint256 n = _u(".leafCount");
        for (uint256 i = 0; i < n; i++) {
            address claimant = vm.parseJsonAddress(json, string.concat(".entries[", vm.toString(i), "].claimant"));
            uint256 amount = _u(string.concat(".entries[", vm.toString(i), "].amount"));
            bytes32 salt = vm.parseJsonBytes32(json, string.concat(".entries[", vm.toString(i), "].salt"));
            bytes32[] memory proof =
                vm.parseJsonBytes32Array(json, string.concat(".entries[", vm.toString(i), "].proof"));

            uint256 before = usdg.balanceOf(claimant);

            vm.prank(claimant);
            payroll.claim(runId, i, amount, salt, proof);

            assertEq(usdg.balanceOf(claimant) - before, amount, "wrong amount paid");
        }

        // every JS-generated package was claimed, and THIS run is exactly drained
        (,,, uint256 deposited, uint256 claimed,) = payroll.runs(runId);
        assertEq(claimed, deposited, "not fully claimed");
        assertEq(payroll.remaining(runId), 0, "run still has funds");

        // the contract balance is the placeholder runs' deposits only — this run left nothing
        assertEq(
            usdg.balanceOf(address(payroll)),
            (runId - 1) * 1e6,
            "this run should have released everything it held"
        );
    }
}

/// @dev Minimal hex helper so the test can compare the tag string.
///      Named HexTag (not Strings) to avoid colliding with forge-std's Strings library.
library HexTag {
    bytes16 private constant HEX = "0123456789abcdef";

    function hexOf(bytes32 value) internal pure returns (string memory) {
        bytes memory out = new bytes(66);
        out[0] = "0";
        out[1] = "x";
        for (uint256 i = 0; i < 32; i++) {
            uint8 b = uint8(value[i]);
            out[2 + i * 2] = HEX[b >> 4];
            out[3 + i * 2] = HEX[b & 0x0f];
        }
        return string(out);
    }
}
